name: AleloChallenge
options:
  bundleIdPrefix: com.samuel.AleloChallenge
  createIntermediateGroups: true
    
packages:
  DependencyInjection:
    path: DependencyInjection
  Commons:
    path: Commons
  SDWebImage:
    url: https://github.com/SDWebImage/SDWebImage.git
    from: 5.13.0
    
targets:
  Application:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    templates:
      - groupable
    templateAttributes:
      groupName: App
      targetName: Application
    dependencies:
      - target: Core
      - target: ModuleIntegrator
      - target: Store
    scheme:
      testTargets:
        - ServiceTests
      gatherCoverageData: true
 
  Core:
    templates:
      - framework
      - groupable
    templateAttributes:
      groupName: Core
      targetName: Core
    dependencies:
      - target: Service
      - package: DependencyInjection

  ModuleIntegrator:
    templates:
      - framework
      - groupable
    templateAttributes:
      groupName: Core
      targetName: ModuleIntegrator
    dependencies:
      - target: Core
      - target: Service
      - target: Store
      - package: DependencyInjection
      
  Service:
    templates:
      - framework
      - groupable
      - swiftgen-generated
    templateAttributes:
      groupName: Service
      targetName: Service
    dependencies:
      - package: DependencyInjection

  ServiceTests:
    templates:
      - unit-tests
      - groupable
    templateAttributes:
      groupName: Service
      targetName: ServiceTests
    dependencies:
      - target: Service
      - package: DependencyInjection
      - target: ModuleIntegrator

  Store:
    templates:
      - framework
      - groupable
      - swiftgen-generated
    templateAttributes:
      groupName: Store
      targetName: Store
    dependencies:
      - target: Core
      - target: Service
      - package: DependencyInjection
      - package: Commons
      - package: SDWebImage
        
targetTemplates:
  groupable:
    sources:
      - path: ${groupName}/${targetName}
    group: ${groupName}
    
  framework:
    deploymentTarget: "14.0"
    platform: iOS
    type: framework
    info:
        path: ${groupName}/${targetName}/Resources/Info.plist

  swiftgen-generated:
    preBuildScripts:
      - script: cd ${groupName}/Config && swiftgen
        name: Swiftgen
        inputFiles:
          - ${groupName}/${targetName}/Resources/Assets.xcassets
          - ${groupName}/${targetName}/Resources/Localizable.strings
        outputFiles:
          - ${groupName}/${targetName}/Resources/Generated/Assets.swift
          - ${groupName}/${targetName}/Resources/Generated/Strings.swift

  unit-tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    info:
        path: ${groupName}/${targetName}/Info.plist
